#! /bin/sh
# 
# Abort if any command returns an error value
set -e

# This script is called before this version of this package is installed.
# When this script is called, the package's files have not been unpacked
# yet.


get_hostname() {
    HOSTNAME=`hostname --all-fqdns`
    if [ -z ${HOSTNAME}  ]
    then
        HOSTNAME=`hostname`
    fi

    if [ -z ${HOSTNAME}  ] 
    then
        HOSTNAME="localhost"
    fi

    HOSTNAME="$(echo "${HOSTNAME}" | tr -d '[[:space:]]')"    
    # return hostname
    echo "$HOSTNAME"
}


case "$1" in
  install)
   
    ;;
  upgrade)
    # About to upgrade this package from version $2 TO THIS VERSION.
    # "prerm upgrade" has already been called for the old version of
    # this package.
    # discart old certificates - for 1.0.2
    HOSTNAME=$(get_hostname)
    rm -f /usr/local/share/ca-certificates/$HOSTNAME 
    rm -f /etc/ssl/certs/odn-cert.pem
    rm -f /etc/ssl/private/odn-key.pem
    update-ca-certificates --fresh
    
    ;;
  abort-upgrade)
    # Back out of an attempt to upgrade this package FROM THIS VERSION to
    # version $2.  Undo the effects of "postrm upgrade $2".

    ;;
  *) echo "$0: didn't understand being called with \`$1'" 1>&2
     exit 1;;
esac

exit 0